### ISSUE TITLE
Upload fails in iOS 8

### ISSUE THREAD

**Issue by detj** [leftshifters/clipboard#48]
![img_0545](https://cloud.githubusercontent.com/assets/280236/4302299/9d8565e6-3e58-11e4-8963-9e2a96b5e7a1.png)

**Comment by detj** [comment]
Stack trace
```
Error: invalid signature: 0x80014
    at /home/noder/sites/clipboard/node_modules/unzip/lib/parse.js:59:13
    at Immediate.wrapped [as _onImmediate] (/home/noder/sites/clipboard/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```
